// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://loewsxjiajufdrzkhykx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxvZXdzeGppYWp1ZmRyemtoeWt4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxMDc2NjgsImV4cCI6MjA2MTY4MzY2OH0.5CN5ZF5aukbm3nQ5rniZ7zYyPHzZhKzxmArwKRDzEFA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);